Reuse existing subscriptions
kaspernj/api_maker pull request #432
Opened 2020-11-27 13:40 UTC by AndersGM

2020-12-04 10:02 UTC, kaspernj reviewed
I am not sure how this ended up in so many lines of code?

2020-12-04 10:02 UTC, kaspernj commented on ruby-gem/lib/api_maker/javascript/cable-connection-pool.js
> +      if (!this.upcomingSubscriptions[modelName]["events"])
Why was this changed? It doesn't seem like it was necessary?

2020-12-04 10:11 UTC, kaspernj requested changes
We need a ton of specs for this. This is very hard to review because of all the irrelevant changes.

2020-12-18 16:48 UTC, AndersGM commented on ruby-gem/lib/api_maker/javascript/cable-connection-pool.js
> +      if (!this.upcomingSubscriptions[modelName]["events"])
There is added a condition https://github.com/kaspernj/api_maker/pull/432/files#diff-960a4d8e1fbcdce8c8ca074c9ac52f5b42870df68d5c66988cfb656903e7dcbfR93 that checks whether the subscription can be added to an existing connection. So this code had to be indented - if that is the question?

2020-12-21 18:26 UTC, kaspernj commented
Let stop working on this for now :-)

2021-03-12 07:32 UTC, closed without merging