Validation errors for passwords and other encrypted fields
kaspernj/api_maker pull request #571
Opened 2021-05-25 13:02 UTC by AndersGM

https://app.asana.com/0/1153435032856801/1200343177746821

2021-05-25 13:04 UTC, kaspernj commented on ruby-gem/app/services/api_maker/validation_errors_generator_service.rb
> +    if model.attribute_names.include?(attribute_name.to_s) || model.attribute_names.include?("encrypted_#{attribute_name}")
I would argue it would be wrong to call it an attribute, if it is indeed an attribute. Maybe a virtual attribute? Or encrypted attribute?

Would an encrypted attribute always be named like that?

2021-05-25 13:18 UTC, AndersGM commented on ruby-gem/app/services/api_maker/validation_errors_generator_service.rb
> +    if model.attribute_names.include?(attribute_name.to_s) || model.attribute_names.include?("encrypted_#{attribute_name}")
Decided to use whitelisting instead

2021-05-25 18:50 UTC, kaspernj requested changes

2021-05-25 18:50 UTC, kaspernj commented on ruby-gem/app/services/api_maker/validation_errors_generator_service.rb
> +        model.class.const_get(:ADDITIONAL_ATTRIBUTES_FOR_VALIDATION_ERRORS).include?(attribute_name)
Couldn't this work without the horrible indentation?
```suggestion
    elsif model.class.const_get(:ADDITIONAL_ATTRIBUTES_FOR_VALIDATION_ERRORS)&.include?(attribute_name)
```

2021-05-25 18:50 UTC, kaspernj commented on ruby-gem/app/services/api_maker/validation_errors_generator_service.rb
> +      :attribute
So here we tell that something is an attribute without that it actually is. We hack it in order to make it behave a certain way. That is not the way we should solve things :-)

2021-05-26 07:50 UTC, AndersGM commented on ruby-gem/app/services/api_maker/validation_errors_generator_service.rb
> +        model.class.const_get(:ADDITIONAL_ATTRIBUTES_FOR_VALIDATION_ERRORS).include?(attribute_name)
Sadly no :( it will raise a name error exception

2021-05-26 07:50 UTC, AndersGM commented on ruby-gem/app/services/api_maker/validation_errors_generator_service.rb
> +      :attribute
I've renamed it to additional_attribute_for_validation :-)

2021-05-26 07:54 UTC, kaspernj approved these changes

2021-05-26 07:55 UTC, kaspernj commented on ruby-gem/app/services/api_maker/validation_errors_generator_service.rb
> +  def perform
This will require a certain version of ServicePattern which should be set in the .gemspec file. We also have to release another version of it first. If we wanna release before that, then this would have to still be called execute?

2021-05-26 08:02 UTC, AndersGM commented on ruby-gem/app/services/api_maker/validation_errors_generator_service.rb
> +  def perform
Yes I will create a separate PR for that :-)

2021-05-26 08:18 UTC, kaspernj approved these changes

2021-05-26 08:18 UTC, merged