Check for attribute in validation error
kaspernj/api_maker pull request #596
Opened 2021-06-22 10:33 UTC by AndersGM

https://app.asana.com/0/1153620213598883/1200490015463714

2021-06-22 19:07 UTC, kaspernj approved these changes

2021-06-22 19:07 UTC, kaspernj commented on npm-api-maker/src/base-model.cjs
> +      throw new ValidationError(validationErrors, error.args)
`args` should always be present, right?
```suggestion
      throw new ValidationError(validationErrors, digg(error, "args"))
```

2021-06-22 19:08 UTC, kaspernj commented
There is a conflict currently :'-(

2021-06-22 19:27 UTC, AndersGM commented
@kaspernj Not anymore :-)

2021-06-23 08:01 UTC, kaspernj commented on npm-api-maker/src/commands-pool.cjs
>          } else {
This is how we usually distinguish what the command response is. Shouldn't we continue this pattern instead of looking for specific keys?
```suggestion
        } else if (commandResponse.type == "validation_error") {
```

2021-06-23 12:12 UTC, kaspernj requested changes

2021-06-23 12:12 UTC, kaspernj commented on npm-api-maker/src/commands-pool.cjs
> +    commandData.reject(new CustomError("Command failed", {response: commandResponseData}))
This should return the error object, right?
```suggestion
    commandData.reject(error)
```

2021-06-24 13:27 UTC, AndersGM commented on npm-api-maker/src/commands-pool.cjs
> +    commandData.reject(new CustomError("Command failed", {response: commandResponseData}))
That should be fixed now. I've also changed the spec since it shouldn't pass without your suggestion :-)

2021-06-24 14:17 UTC, kaspernj commented on ruby-gem/spec/dummy/app/api_maker/commands/projects/create_project.rb
> +    end
```suggestion

    if project.save
      succeed!
    else
      failure_save_response(model: project, params: params)
    end
```

2021-06-25 09:44 UTC, kaspernj approved these changes

2021-06-25 09:44 UTC, merged

2021-06-25 09:45 UTC, kaspernj commented
Released in version 1.0.100